import { useApp } from '../core';

export function MorePanel(){
  var _c:any=useApp();
  var {borderC,buildMobileMenuItems,cardBg,dark,expenseColor,isMobile,setMobileMenu,setSettingsPage,setTab,subC,textC,translateUiRuntimeText}:any=_c;

    function capMenuLabel(v){v=String(v||"");return v?v.charAt(0).toLocaleUpperCase()+v.slice(1):v;}
    var menuSubs={stats:translateUiRuntimeText("Analisi, trend e confronti"),consulenteAI:translateUiRuntimeText("Analisi e domande"),patrimonio:translateUiRuntimeText("Asset, conti e storico"),budget:translateUiRuntimeText("Piano mensile e risparmio"),goals:translateUiRuntimeText("Risparmi e target"),alerts:translateUiRuntimeText("Soglie e avvisi"),share:translateUiRuntimeText("Progetti, costi condivisi e saldi"),debtCredits:translateUiRuntimeText("Prestiti, rimborsi e scadenze"),shopping:translateUiRuntimeText("Liste, prodotti e acquisti"),appunti:translateUiRuntimeText("Note, documenti e coordinate"),settings:translateUiRuntimeText("Profilo, dati e preferenze")};
    var items=buildMobileMenuItems().map(function(item){return {...item,sub:menuSubs[item.id]||""};});
    return <div style={{display:"flex",flexDirection:"column",gap:14}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12}}><div style={{fontSize:20,fontWeight:900,color:textC}}>{translateUiRuntimeText("Altro")}</div>{isMobile&&<button onClick={function(){setTab("home");setMobileMenu(false);}} aria-label="Chiudi menu" style={{width:36,height:36,borderRadius:12,border:"1px solid "+borderC,background:cardBg,color:"#F87171",fontSize:22,fontWeight:900,cursor:"pointer",lineHeight:1}}>×</button>}</div><div style={{display:"grid",gridTemplateColumns:isMobile?"1fr":"1fr 1fr",gap:12}}>{items.map(function(item){return <button key={item.id} onClick={function(){setTab(item.id);setSettingsPage(null);setMobileMenu(false);}} style={{position:"relative",textAlign:"left",background:cardBg,border:"1px solid "+borderC,borderRadius:16,padding:"15px 16px",display:"flex",alignItems:"center",gap:12,cursor:"pointer",color:textC,boxShadow:dark?"none":"0 4px 14px rgba(0,0,0,0.05)"}}><span style={{fontSize:24,width:32,textAlign:"center"}}>{item.icon}</span><span style={{flex:1}}><span style={{display:"block",fontSize:15,fontWeight:800}}>{capMenuLabel(item.label)}</span><span style={{display:"block",fontSize:12,color:subC,marginTop:2}}>{item.sub}</span></span>{item.badge>0&&<span style={{position:"absolute",right:12,top:12,background:expenseColor,color:"#fff",borderRadius:"50%",width:20,height:20,fontSize:11,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:700}}>{item.badge}</span>}</button>;})}</div></div>;
  }
