const keys=['title','intro','when','if','then','all','any','condition','action','probe','contains','equals','starts','notContains','notEquals','greater','less','description','category','payment','amount','direction','transactionType','source','expense','income','movement','single','installment','receipt','manual','bulk','voice','assistant','tool','tags','information','confirmation','none','error','limit','hint','matched','unmatched','priority','testHint','defaultFields'] as const;
export const automaticRulesRows={
it:['Regole automatiche','Completa i movimenti e mostra avvisi personalizzati','QUANDO','SE','ALLORA','Tutte','Almeno una','Aggiungi condizione','Aggiungi azione','Testa Regola','Contiene','Uguale a','Inizia con','Non contiene','Diverso da','Maggiore di','Minore di','Descrizione','Categoria','Pagamento','Importo','Entrata/Uscita','Tipo transazione','Origine','Uscita','Entrata','Ogni movimento','Singola','Rateizzata','Scontrino','Manuale','Multiplo','Voce','Agente AI','Tool','Tag','Informativo','Di conferma','Nessuno','Operazione non riuscita. Controlla i campi o riapri la regola.','Hai raggiunto il limite di regole del tuo piano.','I dati scelti da te prevalgono sulle regole. In caso di conflitto vale la prima regola; le modifiche non attivano altre regole.','Regola applicabile','Regola non applicabile','Trascina per ordinare oppure usa le frecce.','La prova non salva movimenti e non mostra gli alert.','Categoria e pagamento della prova sono valori predefiniti, sostituibili dalle regole.'],
en:['Automatic rules','Complete transactions and show custom alerts','WHEN','IF','THEN','All','Any','Add condition','Add action','Test Rule','Contains','Equals','Starts with','Does not contain','Not equal','Greater than','Less than','Description','Category','Payment','Amount','Income/Expense','Transaction type','Source','Expense','Income','Any transaction','Single','Installment','Receipt','Manual','Bulk','Voice','AI Agent','Tools','Tags','Information','Confirmation','None','Unable to complete. Check the fields or reopen the rule.','You have reached your plan’s rule limit.','Your choices take precedence. The first rule wins conflicts; changes do not trigger other rules.','Rule matches','Rule does not match','Drag to reorder or use the arrows.','Testing saves no transactions and displays no alerts.','Test category and payment are defaults that rules can replace.'],
es:['Reglas automáticas','Completa movimientos y muestra avisos personalizados','CUANDO','SI','ENTONCES','Todas','Al menos una','Añadir condición','Añadir acción','Probar Regla','Contiene','Igual a','Empieza por','No contiene','Distinto de','Mayor que','Menor que','Descripción','Categoría','Pago','Importe','Ingreso/Gasto','Tipo de transacción','Origen','Gasto','Ingreso','Cada movimiento','Única','A plazos','Recibo','Manual','Múltiple','Voz','Agente IA','Herramientas','Etiquetas','Informativo','Confirmación','Ninguno','No se pudo completar. Revisa los campos o abre la regla de nuevo.','Has alcanzado el límite de reglas de tu plan.','Tus elecciones tienen prioridad. En conflictos gana la primera regla; los cambios no activan otras reglas.','La regla coincide','La regla no coincide','Arrastra para ordenar o usa las flechas.','La prueba no guarda movimientos ni muestra avisos.','La categoría y el pago de prueba son valores predeterminados que las reglas pueden sustituir.'],
fr:['Règles automatiques','Complétez les opérations et affichez des alertes personnalisées','QUAND','SI','ALORS','Toutes','Au moins une','Ajouter une condition','Ajouter une action','Tester la règle','Contient','Égal à','Commence par','Ne contient pas','Différent de','Supérieur à','Inférieur à','Description','Catégorie','Paiement','Montant','Revenu/Dépense','Type de transaction','Origine','Dépense','Revenu','Chaque opération','Unique','Échelonnée','Ticket','Manuelle','Multiple','Voix','Agent IA','Outils','Étiquettes','Information','Confirmation','Aucune','Échec de l’opération. Vérifiez les champs ou rouvrez la règle.','Vous avez atteint la limite de règles de votre forfait.','Vos choix sont prioritaires. La première règle résout les conflits ; les changements ne déclenchent pas d’autres règles.','La règle correspond','La règle ne correspond pas','Glissez pour réordonner ou utilisez les flèches.','Le test ne sauvegarde aucune opération et n’affiche aucune alerte.','La catégorie et le paiement du test sont des valeurs par défaut remplaçables.'],
de:['Automatische Regeln','Buchungen ergänzen und eigene Hinweise anzeigen','WENN','FALLS','DANN','Alle','Mindestens eine','Bedingung hinzufügen','Aktion hinzufügen','Regel testen','Enthält','Gleich','Beginnt mit','Enthält nicht','Ungleich','Größer als','Kleiner als','Beschreibung','Kategorie','Zahlung','Betrag','Einnahme/Ausgabe','Buchungsart','Quelle','Ausgabe','Einnahme','Jede Buchung','Einzeln','Raten','Beleg','Manuell','Mehrfach','Sprache','KI-Agent','Tools','Tags','Information','Bestätigung','Keine','Vorgang fehlgeschlagen. Prüfe die Felder oder öffne die Regel erneut.','Du hast das Regellimit deines Tarifs erreicht.','Deine Auswahl hat Vorrang. Bei Konflikten gilt die erste Regel; Änderungen lösen keine weiteren Regeln aus.','Regel trifft zu','Regel trifft nicht zu','Zum Sortieren ziehen oder die Pfeile verwenden.','Der Test speichert keine Buchungen und zeigt keine Hinweise.','Kategorie und Zahlung im Test sind ersetzbare Standardwerte.'],
pt:['Regras automáticas','Completa movimentos e mostra avisos personalizados','QUANDO','SE','ENTÃO','Todas','Pelo menos uma','Adicionar condição','Adicionar ação','Testar Regra','Contém','Igual a','Começa por','Não contém','Diferente de','Maior que','Menor que','Descrição','Categoria','Pagamento','Valor','Receita/Despesa','Tipo de transação','Origem','Despesa','Receita','Cada movimento','Única','Prestações','Recibo','Manual','Múltiplo','Voz','Agente IA','Ferramentas','Etiquetas','Informativo','Confirmação','Nenhum','Não foi possível concluir. Verifique os campos ou reabra a regra.','Atingiu o limite de regras do seu plano.','As suas escolhas têm prioridade. Em conflitos vale a primeira regra; as alterações não ativam outras regras.','A regra corresponde','A regra não corresponde','Arraste para ordenar ou use as setas.','O teste não guarda movimentos nem mostra avisos.','A categoria e o pagamento de teste são valores predefinidos substituíveis.'],
pl:['Reguły automatyczne','Uzupełniaj transakcje i wyświetlaj własne alerty','KIEDY','JEŚLI','WTEDY','Wszystkie','Co najmniej jeden','Dodaj warunek','Dodaj działanie','Testuj regułę','Zawiera','Równe','Zaczyna się od','Nie zawiera','Różne od','Większe niż','Mniejsze niż','Opis','Kategoria','Płatność','Kwota','Przychód/Wydatek','Typ transakcji','Źródło','Wydatek','Przychód','Każda transakcja','Pojedyncza','Raty','Paragon','Ręcznie','Wiele','Głos','Agent AI','Narzędzia','Tagi','Informacja','Potwierdzenie','Brak','Operacja nie powiodła się. Sprawdź pola lub otwórz regułę ponownie.','Osiągnięto limit reguł planu.','Twój wybór ma pierwszeństwo. Konflikty rozstrzyga pierwsza reguła; zmiany nie uruchamiają kolejnych reguł.','Reguła pasuje','Reguła nie pasuje','Przeciągnij lub użyj strzałek, aby zmienić kolejność.','Test nie zapisuje transakcji ani nie pokazuje alertów.','Kategoria i płatność testu są domyślnymi wartościami, które reguły mogą zastąpić.'],
nl:['Automatische regels','Vul transacties aan en toon eigen meldingen','WANNEER','ALS','DAN','Alle','Minstens één','Voorwaarde toevoegen','Actie toevoegen','Regel testen','Bevat','Gelijk aan','Begint met','Bevat niet','Niet gelijk','Groter dan','Kleiner dan','Omschrijving','Categorie','Betaling','Bedrag','Inkomst/Uitgave','Transactietype','Bron','Uitgave','Inkomst','Elke transactie','Eenmalig','Termijnen','Bon','Handmatig','Meerdere','Spraak','AI-agent','Tools','Tags','Informatie','Bevestiging','Geen','De bewerking is mislukt. Controleer de velden of open de regel opnieuw.','Je hebt het regellimiet van je abonnement bereikt.','Je keuzes gaan voor. Bij conflicten geldt de eerste regel; wijzigingen activeren geen andere regels.','Regel komt overeen','Regel komt niet overeen','Sleep om te ordenen of gebruik de pijlen.','De test slaat geen transacties op en toont geen meldingen.','Categorie en betaling in de test zijn vervangbare standaardwaarden.'],
ro:['Reguli automate','Completează tranzacțiile și afișează alerte personalizate','CÂND','DACĂ','ATUNCI','Toate','Cel puțin una','Adaugă condiție','Adaugă acțiune','Testează regula','Conține','Egal cu','Începe cu','Nu conține','Diferit de','Mai mare decât','Mai mic decât','Descriere','Categorie','Plată','Sumă','Venit/Cheltuială','Tip tranzacție','Sursă','Cheltuială','Venit','Orice tranzacție','Unică','Rate','Bon','Manual','Multiplu','Voce','Agent AI','Instrumente','Etichete','Informativ','Confirmare','Niciuna','Operațiunea a eșuat. Verifică câmpurile sau redeschide regula.','Ai atins limita de reguli a planului.','Alegerile tale au prioritate. Prima regulă rezolvă conflictele; modificările nu declanșează alte reguli.','Regula se potrivește','Regula nu se potrivește','Trage pentru reordonare sau folosește săgețile.','Testul nu salvează tranzacții și nu afișează alerte.','Categoria și plata testului sunt valori implicite înlocuibile.'],
el:['Αυτόματοι κανόνες','Συμπλήρωση συναλλαγών και προσαρμοσμένες ειδοποιήσεις','ΟΤΑΝ','ΕΑΝ','ΤΟΤΕ','Όλες','Τουλάχιστον μία','Προσθήκη συνθήκης','Προσθήκη ενέργειας','Δοκιμή κανόνα','Περιέχει','Ίσο με','Αρχίζει με','Δεν περιέχει','Διαφορετικό από','Μεγαλύτερο από','Μικρότερο από','Περιγραφή','Κατηγορία','Πληρωμή','Ποσό','Έσοδο/Έξοδο','Τύπος συναλλαγής','Προέλευση','Έξοδο','Έσοδο','Κάθε συναλλαγή','Μεμονωμένη','Δόσεις','Απόδειξη','Χειροκίνητα','Πολλαπλές','Φωνή','Πράκτορας AI','Εργαλεία','Ετικέτες','Πληροφορία','Επιβεβαίωση','Καμία','Η ενέργεια απέτυχε. Ελέγξτε τα πεδία ή ανοίξτε ξανά τον κανόνα.','Φτάσατε το όριο κανόνων του προγράμματός σας.','Οι επιλογές σας προηγούνται. Σε σύγκρουση ισχύει ο πρώτος κανόνας· οι αλλαγές δεν ενεργοποιούν άλλους κανόνες.','Ο κανόνας ταιριάζει','Ο κανόνας δεν ταιριάζει','Σύρετε για ταξινόμηση ή χρησιμοποιήστε τα βέλη.','Η δοκιμή δεν αποθηκεύει συναλλαγές και δεν εμφανίζει ειδοποιήσεις.','Η κατηγορία και η πληρωμή της δοκιμής είναι αντικαταστάσιμες προεπιλογές.']
};
export function rulesText(lang:string,key:typeof keys[number]){return (automaticRulesRows[lang]||automaticRulesRows.it)[keys.indexOf(key)];}
export const rulesExtraRows={it:['Duplica','Disattiva'],en:['Duplicate','Disable'],es:['Duplicar','Desactivar'],fr:['Dupliquer','Désactiver'],de:['Duplizieren','Deaktivieren'],pt:['Duplicar','Desativar'],pl:['Duplikuj','Wyłącz'],nl:['Dupliceren','Uitschakelen'],ro:['Duplică','Dezactivează'],el:['Αντιγραφή','Απενεργοποίηση']};
export function rulesExtraText(lang:string,key:string){const index=['Duplica','Disattiva'].indexOf(key);return index<0?null:(rulesExtraRows[lang]||rulesExtraRows.it)[index];}


const automaticRulesUiRows:any={
  it:{createRule:'Crea Regola',ruleSingular:'Regola automatica',whenSubtitle:'Definisci l’evento che avvia la regola',ifSubtitle:'Aggiungi le condizioni che devono essere verificate',thenSubtitle:'Scegli cosa deve fare la regola',messagePlaceholder:'Sei sicuro?',testRule:'Testa Regola'},
  en:{createRule:'Create Rule',ruleSingular:'Automatic Rule',whenSubtitle:'Define the event that starts the rule',ifSubtitle:'Add the conditions that must be met',thenSubtitle:'Choose what the rule should do',messagePlaceholder:'Are you sure?',testRule:'Test Rule'},
  es:{createRule:'Crear Regla',ruleSingular:'Regla automática',whenSubtitle:'Define el evento que inicia la regla',ifSubtitle:'Añade las condiciones que deben cumplirse',thenSubtitle:'Elige lo que debe hacer la regla',messagePlaceholder:'¿Estás seguro?',testRule:'Probar regla'},
  fr:{createRule:'Créer une Règle',ruleSingular:'Règle automatique',whenSubtitle:'Définissez l’événement qui lance la règle',ifSubtitle:'Ajoutez les conditions qui doivent être remplies',thenSubtitle:'Choisissez ce que la règle doit faire',messagePlaceholder:'Êtes-vous sûr ?',testRule:'Tester la règle'},
  de:{createRule:'Regel erstellen',ruleSingular:'Automatische Regel',whenSubtitle:'Lege das Ereignis fest, das die Regel startet',ifSubtitle:'Füge die Bedingungen hinzu, die erfüllt sein müssen',thenSubtitle:'Wähle aus, was die Regel tun soll',messagePlaceholder:'Bist du sicher?',testRule:'Regel testen'},
  pt:{createRule:'Criar Regra',ruleSingular:'Regra automática',whenSubtitle:'Define o evento que inicia a regra',ifSubtitle:'Adiciona as condições que devem ser cumpridas',thenSubtitle:'Escolhe o que a regra deve fazer',messagePlaceholder:'Tens a certeza?',testRule:'Testar regra'},
  pl:{createRule:'Utwórz regułę',ruleSingular:'Reguła automatyczna',whenSubtitle:'Określ zdarzenie uruchamiające regułę',ifSubtitle:'Dodaj warunki, które muszą zostać spełnione',thenSubtitle:'Wybierz, co ma zrobić reguła',messagePlaceholder:'Czy na pewno?',testRule:'Testuj regułę'},
  nl:{createRule:'Regel aanmaken',ruleSingular:'Automatische regel',whenSubtitle:'Bepaal welke gebeurtenis de regel start',ifSubtitle:'Voeg de voorwaarden toe waaraan moet worden voldaan',thenSubtitle:'Kies wat de regel moet doen',messagePlaceholder:'Weet je het zeker?',testRule:'Regel testen'},
  ro:{createRule:'Creează regulă',ruleSingular:'Regulă automată',whenSubtitle:'Definește evenimentul care pornește regula',ifSubtitle:'Adaugă condițiile care trebuie îndeplinite',thenSubtitle:'Alege ce trebuie să facă regula',messagePlaceholder:'Ești sigur?',testRule:'Testează regula'},
  el:{createRule:'Δημιουργία κανόνα',ruleSingular:'Αυτόματος κανόνας',whenSubtitle:'Ορίστε το γεγονός που ενεργοποιεί τον κανόνα',ifSubtitle:'Προσθέστε τις συνθήκες που πρέπει να ισχύουν',thenSubtitle:'Επιλέξτε τι πρέπει να κάνει ο κανόνας',messagePlaceholder:'Είσαι σίγουρος;',testRule:'Δοκιμή κανόνα'}
};
export function rulesUiText(lang:string,key:'createRule'|'ruleSingular'|'whenSubtitle'|'ifSubtitle'|'thenSubtitle'|'messagePlaceholder'|'testRule'){return (automaticRulesUiRows[lang]||automaticRulesUiRows.it)[key];}
