const keys = ['period','scope','month','future','compare','previous','previousYear','average6','average12','achievement','rate','difference','standard','monthlyOverride','useStandard','standardFrom','futureHint','details','achievementHelp','rateHelp'] as const;
const rows: Record<string,string[]> = {
 it:['Periodo','Applica le modifiche','Solo questo mese','Da questo mese in poi','Confronta con','Mese precedente','Stesso mese dell’anno precedente','Media ultimi 6 mesi','Media ultimi 12 mesi','Raggiungimento piano','Tasso di risparmio reale','Scostamento del risparmio reale'],
 en:['Period','Apply changes','This month only','From this month onward','Compare with','Previous month','Same month last year','Last 6 months average','Last 12 months average','Plan achievement','Actual savings rate','Actual savings difference'],
 es:['Periodo','Aplicar cambios','Solo este mes','Desde este mes en adelante','Comparar con','Mes anterior','Mismo mes del año anterior','Media de los últimos 6 meses','Media de los últimos 12 meses','Cumplimiento del plan','Tasa de ahorro real','Diferencia del ahorro real'],
 fr:['Période','Appliquer les modifications','Ce mois uniquement','À partir de ce mois','Comparer avec','Mois précédent','Même mois de l’année précédente','Moyenne des 6 derniers mois','Moyenne des 12 derniers mois','Réalisation du plan','Taux d’épargne réel','Écart d’épargne réelle'],
 de:['Zeitraum','Änderungen anwenden','Nur diesen Monat','Ab diesem Monat','Vergleichen mit','Vormonat','Gleicher Monat im Vorjahr','Durchschnitt der letzten 6 Monate','Durchschnitt der letzten 12 Monate','Planerfüllung','Tatsächliche Sparquote','Abweichung der tatsächlichen Ersparnis'],
 pt:['Período','Aplicar alterações','Apenas este mês','A partir deste mês','Comparar com','Mês anterior','Mesmo mês do ano anterior','Média dos últimos 6 meses','Média dos últimos 12 meses','Cumprimento do plano','Taxa de poupança real','Diferença da poupança real'],
 pl:['Okres','Zastosuj zmiany','Tylko w tym miesiącu','Od tego miesiąca','Porównaj z','Poprzedni miesiąc','Ten sam miesiąc poprzedniego roku','Średnia z ostatnich 6 miesięcy','Średnia z ostatnich 12 miesięcy','Realizacja planu','Rzeczywista stopa oszczędności','Różnica rzeczywistych oszczędności'],
 nl:['Periode','Wijzigingen toepassen','Alleen deze maand','Vanaf deze maand','Vergelijken met','Vorige maand','Dezelfde maand vorig jaar','Gemiddelde laatste 6 maanden','Gemiddelde laatste 12 maanden','Realisatie van het plan','Werkelijk spaarpercentage','Verschil in werkelijke besparingen'],
 ro:['Perioadă','Aplică modificările','Doar luna aceasta','Începând cu această lună','Compară cu','Luna precedentă','Aceeași lună a anului precedent','Media ultimelor 6 luni','Media ultimelor 12 luni','Îndeplinirea planului','Rata economisirii reale','Diferența economiilor reale'],
 el:['Περίοδος','Εφαρμογή αλλαγών','Μόνο αυτόν τον μήνα','Από αυτόν τον μήνα και μετά','Σύγκριση με','Προηγούμενος μήνας','Ίδιος μήνας πέρυσι','Μέσος όρος τελευταίων 6 μηνών','Μέσος όρος τελευταίων 12 μηνών','Επίτευξη πλάνου','Πραγματικό ποσοστό αποταμίευσης','Διαφορά πραγματικής αποταμίευσης'],
};
const additional: Record<string,string[]> = {
 it:['Budget standard','Budget personalizzato per questo mese','Torna al Budget standard','Standard in vigore da','Il nuovo standard vale da questo mese in poi. Le eccezioni degli altri mesi restano invariate.','Come leggere i confronti','Raggiungimento piano = risparmio reale / risparmio pianificato. Se il risparmio pianificato è zero, la percentuale non è disponibile.','Tasso di risparmio reale = risparmio reale / entrate effettive. Senza entrate positive, la percentuale non è disponibile.'],
 en:['Standard budget','Custom budget for this month','Use standard budget','Standard effective from','The new standard applies from this month onward. Other monthly exceptions are preserved.','Understanding comparisons','Plan achievement = actual savings / planned savings. When planned savings are zero, the percentage is unavailable.','Actual savings rate = actual savings / actual income. Without positive income, the percentage is unavailable.'],
 es:['Presupuesto estándar','Presupuesto personalizado para este mes','Usar presupuesto estándar','Estándar vigente desde','El nuevo estándar se aplica desde este mes. Se conservan las excepciones de otros meses.','Cómo interpretar las comparaciones','Cumplimiento del plan = ahorro real / ahorro previsto. Si el ahorro previsto es cero, el porcentaje no está disponible.','Tasa de ahorro real = ahorro real / ingresos reales. Sin ingresos positivos, el porcentaje no está disponible.'],
 fr:['Budget standard','Budget personnalisé pour ce mois','Utiliser le budget standard','Standard applicable depuis','Le nouveau standard s’applique à partir de ce mois. Les exceptions des autres mois sont conservées.','Comprendre les comparaisons','Réalisation du plan = épargne réelle / épargne prévue. Si l’épargne prévue est nulle, le pourcentage est indisponible.','Taux d’épargne réel = épargne réelle / revenus réels. Sans revenus positifs, le pourcentage est indisponible.'],
 de:['Standardbudget','Individuelles Budget für diesen Monat','Standardbudget verwenden','Standard gültig ab','Der neue Standard gilt ab diesem Monat. Ausnahmen anderer Monate bleiben erhalten.','Vergleiche verstehen','Planerfüllung = tatsächliche Ersparnis / geplante Ersparnis. Bei einer geplanten Ersparnis von null ist kein Prozentsatz verfügbar.','Tatsächliche Sparquote = tatsächliche Ersparnis / tatsächliches Einkommen. Ohne positives Einkommen ist kein Prozentsatz verfügbar.'],
 pt:['Orçamento padrão','Orçamento personalizado para este mês','Usar orçamento padrão','Padrão em vigor desde','O novo padrão aplica-se a partir deste mês. As exceções de outros meses são preservadas.','Como interpretar as comparações','Cumprimento do plano = poupança real / poupança planeada. Se a poupança planeada for zero, a percentagem não está disponível.','Taxa de poupança real = poupança real / rendimentos reais. Sem rendimentos positivos, a percentagem não está disponível.'],
 pl:['Budżet standardowy','Budżet indywidualny na ten miesiąc','Użyj budżetu standardowego','Standard obowiązuje od','Nowy standard obowiązuje od tego miesiąca. Wyjątki dla innych miesięcy pozostają bez zmian.','Jak odczytywać porównania','Realizacja planu = rzeczywiste oszczędności / planowane oszczędności. Przy zerowych planowanych oszczędnościach procent jest niedostępny.','Rzeczywista stopa oszczędności = rzeczywiste oszczędności / rzeczywiste dochody. Bez dodatnich dochodów procent jest niedostępny.'],
 nl:['Standaardbudget','Aangepast budget voor deze maand','Standaardbudget gebruiken','Standaard van kracht vanaf','De nieuwe standaard geldt vanaf deze maand. Uitzonderingen voor andere maanden blijven behouden.','Vergelijkingen begrijpen','Realisatie van het plan = werkelijke besparingen / geplande besparingen. Bij nul geplande besparingen is het percentage niet beschikbaar.','Werkelijk spaarpercentage = werkelijke besparingen / werkelijke inkomsten. Zonder positieve inkomsten is het percentage niet beschikbaar.'],
 ro:['Buget standard','Buget personalizat pentru această lună','Folosește bugetul standard','Standard în vigoare din','Noul standard se aplică începând cu această lună. Excepțiile altor luni se păstrează.','Cum se interpretează comparațiile','Îndeplinirea planului = economii reale / economii planificate. Dacă economiile planificate sunt zero, procentul nu este disponibil.','Rata economisirii reale = economii reale / venituri reale. Fără venituri pozitive, procentul nu este disponibil.'],
 el:['Τυπικός προϋπολογισμός','Προσαρμοσμένος προϋπολογισμός αυτού του μήνα','Χρήση τυπικού προϋπολογισμού','Πρότυπο σε ισχύ από','Το νέο πρότυπο ισχύει από αυτόν τον μήνα. Οι εξαιρέσεις άλλων μηνών διατηρούνται.','Κατανόηση συγκρίσεων','Επίτευξη πλάνου = πραγματική αποταμίευση / προγραμματισμένη αποταμίευση. Όταν η προγραμματισμένη αποταμίευση είναι μηδενική, το ποσοστό δεν είναι διαθέσιμο.','Πραγματικό ποσοστό αποταμίευσης = πραγματική αποταμίευση / πραγματικά έσοδα. Χωρίς θετικά έσοδα, το ποσοστό δεν είναι διαθέσιμο.'],
};
for (const language of Object.keys(rows)) rows[language].push(...additional[language]);
export function budgetText(language: string,key: typeof keys[number]) { return (rows[language]||rows.en)[keys.indexOf(key)]; }
export const budgetTranslationRows=rows;
