import {periodText} from './periodTranslations';
const labels=new Map<string,Parameters<typeof periodText>[1]>([['Metriche e periodo di bilancio','metrics'],['Tipo di periodo','type'],['Mese solare','calendar'],['Mese finanziario','financial'],['Giorno di inizio','day'],['Salva periodo','save'],['Periodo di bilancio aggiornato','saved'],['Saldi','balances']]);
export const generalPeriodInfoRows:Record<string,string[]>={
it:['• Il mese solare va dal primo all’ultimo giorno del mese.\n• Il mese finanziario parte invece dal giorno scelto da te e termina il giorno precedente del mese successivo.\n\nLe transazioni non cambiano: cambia solo il periodo in cui vengono conteggiate.','Reale mostra entrate, uscite e saldo usando gli importi effettivamente registrati nel periodo. Rateizzato distribuisce invece nel tempo le operazioni contrassegnate come rateizzate, mostrando nel periodo solo la quota di competenza prevista dalla rateizzazione.'],
en:['• The calendar month runs from the first to the last day of the month.\n• The financial month starts on the day you choose and ends the day before the same date in the following month.\n\nTransactions do not change: only the period in which they are counted changes.','Actual shows income, expenses and balance using amounts recorded in the period. Installment view spreads transactions marked as installments over time, showing only the share allocated to the period.'],
es:['• El mes natural va del primer al último día del mes.\n• El mes financiero comienza el día que elijas y termina el día anterior a esa misma fecha del mes siguiente.\n\nLas transacciones no cambian: solo cambia el período en el que se contabilizan.','Real muestra ingresos, gastos y saldo con los importes registrados en el periodo. La vista por cuotas distribuye las operaciones marcadas como fraccionadas y muestra solo la parte correspondiente al periodo.'],
fr:['• Le mois civil va du premier au dernier jour du mois.\n• Le mois financier commence le jour que vous choisissez et se termine la veille de cette même date le mois suivant.\n\nLes transactions ne changent pas : seule la période dans laquelle elles sont comptabilisées change.','La vue réelle affiche revenus, dépenses et solde à partir des montants enregistrés dans la période. La vue échelonnée répartit les opérations marquées comme échelonnées et affiche seulement la part de la période.'],
de:['• Der Kalendermonat geht vom ersten bis zum letzten Tag des Monats.\n• Der Finanzmonat beginnt an dem von dir gewählten Tag und endet am Tag vor demselben Datum im Folgemonat.\n\nDie Transaktionen ändern sich nicht: Es ändert sich nur der Zeitraum, in dem sie berücksichtigt werden.','Die tatsächliche Ansicht zeigt Einnahmen, Ausgaben und Saldo anhand der im Zeitraum erfassten Beträge. Die Ratenansicht verteilt als Raten markierte Vorgänge zeitlich und zeigt nur den Anteil des jeweiligen Zeitraums.'],
pt:['• O mês civil vai do primeiro ao último dia do mês.\n• O mês financeiro começa no dia que escolheres e termina no dia anterior à mesma data do mês seguinte.\n\nAs transações não mudam: muda apenas o período em que são contabilizadas.','A vista real mostra receitas, despesas e saldo com os montantes registados no período. A vista em prestações distribui as operações assinaladas como fracionadas e mostra apenas a parte correspondente ao período.'],
pl:['• Miesiąc kalendarzowy trwa od pierwszego do ostatniego dnia miesiąca.\n• Miesiąc finansowy zaczyna się w wybranym przez Ciebie dniu i kończy dzień przed tą samą datą w następnym miesiącu.\n\nTransakcje się nie zmieniają: zmienia się tylko okres, do którego są przypisywane.','Widok rzeczywisty pokazuje przychody, wydatki i saldo według kwot zapisanych w okresie. Widok ratalny rozkłada operacje oznaczone jako raty w czasie i pokazuje tylko część przypisaną do okresu.'],
nl:['• De kalendermaand loopt van de eerste tot de laatste dag van de maand.\n• De financiële maand begint op de dag die je kiest en eindigt op de dag vóór dezelfde datum in de volgende maand.\n\nDe transacties veranderen niet: alleen de periode waarin ze worden meegerekend verandert.','De werkelijke weergave toont inkomsten, uitgaven en saldo met de bedragen die in de periode zijn geregistreerd. De termijnweergave spreidt als termijnen gemarkeerde transacties over de tijd en toont alleen het aandeel van de periode.'],
ro:['• Luna calendaristică începe în prima zi și se termină în ultima zi a lunii.\n• Luna financiară începe în ziua aleasă de tine și se termină cu o zi înainte de aceeași dată din luna următoare.\n\nTranzacțiile nu se modifică: se schimbă doar perioada în care sunt luate în calcul.','Vizualizarea reală arată veniturile, cheltuielile și soldul folosind sumele înregistrate în perioadă. Vizualizarea în rate distribuie în timp operațiunile marcate astfel și arată doar partea aferentă perioadei.'],
el:['• Ο ημερολογιακός μήνας διαρκεί από την πρώτη έως την τελευταία ημέρα του μήνα.\n• Ο οικονομικός μήνας ξεκινά την ημέρα που επιλέγεις και τελειώνει την προηγούμενη ημέρα από την ίδια ημερομηνία του επόμενου μήνα.\n\nΟι συναλλαγές δεν αλλάζουν: αλλάζει μόνο η περίοδος στην οποία υπολογίζονται.','Η πραγματική προβολή δείχνει έσοδα, έξοδα και υπόλοιπο με τα ποσά που καταγράφηκαν στην περίοδο. Η προβολή δόσεων κατανέμει χρονικά τις συναλλαγές που έχουν σημειωθεί ως δόσεις και δείχνει μόνο το μερίδιο της περιόδου.'],
};
export function generalPeriodTranslation(text:string,language:string):string|undefined {
  if (language==='it') return undefined;
  const key=labels.get(text);if(key)return periodText(language,key);
  const index=generalPeriodInfoRows.it.indexOf(text);
  return index<0?undefined:(generalPeriodInfoRows[language]||generalPeriodInfoRows.en)[index];
}
