import {periodText} from './periodTranslations';
const labels=new Map<string,Parameters<typeof periodText>[1]>([['Metriche e periodo di bilancio','metrics'],['Tipo di periodo','type'],['Mese solare','calendar'],['Mese finanziario','financial'],['Giorno di inizio','day'],['Salva periodo','save'],['Periodo di bilancio aggiornato','saved'],['Saldi','balances']]);
export const generalPeriodInfoRows:Record<string,string[]>={
it:['Il Mese solare va dal primo all’ultimo giorno del mese. Il Mese finanziario parte dal giorno che scegli qui sotto, utile ad esempio per far coincidere il periodo con l’accredito dello stipendio. Se quel giorno non esiste in un mese, viene usato l’ultimo giorno disponibile.','Reale mostra entrate, uscite e saldo usando gli importi effettivamente registrati nel periodo. Rateizzato distribuisce invece nel tempo le operazioni contrassegnate come rateizzate, mostrando nel periodo solo la quota di competenza prevista dalla rateizzazione.'],
en:['The calendar month runs from the first to the last day of the month. The financial month starts on the day selected below, for example to match your payday. If that day does not exist in a month, the last available day is used.','Actual shows income, expenses and balance using amounts recorded in the period. Installment view spreads transactions marked as installments over time, showing only the share allocated to the period.'],
es:['El mes natural va del primer al último día del mes. El mes financiero empieza el día elegido abajo, por ejemplo para coincidir con el cobro del sueldo. Si ese día no existe, se usa el último día disponible.','Real muestra ingresos, gastos y saldo con los importes registrados en el periodo. La vista por cuotas distribuye las operaciones marcadas como fraccionadas y muestra solo la parte correspondiente al periodo.'],
fr:['Le mois civil va du premier au dernier jour du mois. Le mois financier commence le jour choisi ci-dessous, par exemple pour correspondre au versement du salaire. Si ce jour n’existe pas, le dernier jour disponible est utilisé.','La vue réelle affiche revenus, dépenses et solde à partir des montants enregistrés dans la période. La vue échelonnée répartit les opérations marquées comme échelonnées et affiche seulement la part de la période.'],
de:['Der Kalendermonat reicht vom ersten bis zum letzten Tag des Monats. Der Finanzmonat beginnt am unten gewählten Tag, etwa passend zum Gehaltseingang. Gibt es diesen Tag nicht, wird der letzte verfügbare Tag verwendet.','Die tatsächliche Ansicht zeigt Einnahmen, Ausgaben und Saldo anhand der im Zeitraum erfassten Beträge. Die Ratenansicht verteilt als Raten markierte Vorgänge zeitlich und zeigt nur den Anteil des jeweiligen Zeitraums.'],
pt:['O mês civil vai do primeiro ao último dia do mês. O mês financeiro começa no dia escolhido abaixo, por exemplo para coincidir com o salário. Se esse dia não existir, é usado o último dia disponível.','A vista real mostra receitas, despesas e saldo com os montantes registados no período. A vista em prestações distribui as operações assinaladas como fracionadas e mostra apenas a parte correspondente ao período.'],
pl:['Miesiąc kalendarzowy trwa od pierwszego do ostatniego dnia miesiąca. Miesiąc finansowy zaczyna się w wybranym poniżej dniu, na przykład w dniu wypłaty. Jeśli taki dzień nie istnieje, używany jest ostatni dostępny dzień.','Widok rzeczywisty pokazuje przychody, wydatki i saldo według kwot zapisanych w okresie. Widok ratalny rozkłada operacje oznaczone jako raty w czasie i pokazuje tylko część przypisaną do okresu.'],
nl:['De kalendermaand loopt van de eerste tot de laatste dag van de maand. De financiële maand begint op de hieronder gekozen dag, bijvoorbeeld je betaaldag. Als die dag niet bestaat, wordt de laatste beschikbare dag gebruikt.','De werkelijke weergave toont inkomsten, uitgaven en saldo met de bedragen die in de periode zijn geregistreerd. De termijnweergave spreidt als termijnen gemarkeerde transacties over de tijd en toont alleen het aandeel van de periode.'],
ro:['Luna calendaristică începe în prima și se termină în ultima zi a lunii. Luna financiară începe în ziua aleasă mai jos, de exemplu pentru a coincide cu salariul. Dacă ziua nu există, se folosește ultima zi disponibilă.','Vizualizarea reală arată veniturile, cheltuielile și soldul folosind sumele înregistrate în perioadă. Vizualizarea în rate distribuie în timp operațiunile marcate astfel și arată doar partea aferentă perioadei.'],
el:['Ο ημερολογιακός μήνας διαρκεί από την πρώτη έως την τελευταία ημέρα του μήνα. Ο οικονομικός μήνας αρχίζει την ημέρα που επιλέγεις παρακάτω, για παράδειγμα την ημέρα μισθοδοσίας. Αν αυτή η ημέρα δεν υπάρχει, χρησιμοποιείται η τελευταία διαθέσιμη.','Η πραγματική προβολή δείχνει έσοδα, έξοδα και υπόλοιπο με τα ποσά που καταγράφηκαν στην περίοδο. Η προβολή δόσεων κατανέμει χρονικά τις συναλλαγές που έχουν σημειωθεί ως δόσεις και δείχνει μόνο το μερίδιο της περιόδου.'],
};
export function generalPeriodTranslation(text:string,language:string):string|undefined {
  if (language==='it') return undefined;
  const key=labels.get(text);if(key)return periodText(language,key);
  const index=generalPeriodInfoRows.it.indexOf(text);
  return index<0?undefined:(generalPeriodInfoRows[language]||generalPeriodInfoRows.en)[index];
}
