const keys = ['title','calendar','financial','day','hint','retroactive','save','saved','keep','type','metrics','balances'] as const;
const rows: Record<string,string[]> = {
  it: ['Periodo di bilancio','Mese solare','Mese finanziario','Giorno di inizio','Puoi scegliere il giorno in cui ricevi normalmente lo stipendio. Se il giorno non esiste, viene usato l’ultimo giorno del mese.','La scelta ricalcola i raggruppamenti di tutto lo storico. Le date e gli importi delle transazioni restano invariati.','Salva periodo','Periodo aggiornato','Mantieni il periodo attuale',"Tipo di periodo","Metriche e periodo di bilancio","Saldi"],
  en: ['Accounting period','Calendar month','Financial month','Start day','You can choose your usual payday. If the day does not exist, the last day of the month is used.','This choice recalculates groupings across your history. Transaction dates and amounts stay unchanged.','Save period','Period updated','Keep current period',"Period type","Metrics and accounting period","Balances"],
  es: ['Periodo contable','Mes natural','Mes financiero','Día de inicio','Puedes elegir el día habitual de cobro. Si el día no existe, se usa el último día del mes.','La elección recalcula las agrupaciones de todo el historial. Las fechas y los importes de las transacciones se mantienen.','Guardar periodo','Periodo actualizado','Mantener el periodo actual',"Tipo de periodo","Métricas y periodo contable","Saldos"],
  fr: ['Période comptable','Mois civil','Mois financier','Jour de début','Vous pouvez choisir votre jour de paie habituel. Si ce jour n’existe pas, le dernier jour du mois est utilisé.','Ce choix recalcule les regroupements de tout l’historique. Les dates et les montants des transactions restent inchangés.','Enregistrer la période','Période mise à jour','Conserver la période actuelle',"Type de période","Indicateurs et période comptable","Soldes"],
  de: ['Abrechnungszeitraum','Kalendermonat','Finanzmonat','Starttag','Du kannst deinen üblichen Zahltag wählen. Gibt es den Tag nicht, wird der letzte Tag des Monats verwendet.','Die Auswahl berechnet die Gruppierungen des gesamten Verlaufs neu. Datum und Betrag der Transaktionen bleiben unverändert.','Zeitraum speichern','Zeitraum aktualisiert','Aktuellen Zeitraum beibehalten',"Zeitraumtyp","Kennzahlen und Abrechnungszeitraum","Salden"],
  pt: ['Período contabilístico','Mês civil','Mês financeiro','Dia de início','Podes escolher o dia habitual de pagamento. Se o dia não existir, é usado o último dia do mês.','A escolha recalcula os agrupamentos de todo o histórico. As datas e os valores das transações não mudam.','Guardar período','Período atualizado','Manter o período atual',"Tipo de período","Métricas e período contabilístico","Saldos"],
  pl: ['Okres rozliczeniowy','Miesiąc kalendarzowy','Miesiąc finansowy','Dzień rozpoczęcia','Możesz wybrać zwykły dzień wypłaty. Jeśli dany dzień nie istnieje, używany jest ostatni dzień miesiąca.','Wybór przelicza grupowanie całej historii. Daty i kwoty transakcji pozostają bez zmian.','Zapisz okres','Okres zaktualizowany','Zachowaj bieżący okres',"Typ okresu","Wskaźniki i okres rozliczeniowy","Salda"],
  nl: ['Boekhoudperiode','Kalendermaand','Financiële maand','Begindag','Je kunt je gebruikelijke betaaldag kiezen. Als de dag niet bestaat, wordt de laatste dag van de maand gebruikt.','Deze keuze herberekent de groeperingen van je volledige geschiedenis. Transactiedatums en bedragen blijven gelijk.','Periode opslaan','Periode bijgewerkt','Huidige periode behouden',"Periodetype","Statistieken en boekhoudperiode","Saldi"],
  ro: ['Perioadă contabilă','Lună calendaristică','Lună financiară','Zi de început','Poți alege ziua obișnuită de salariu. Dacă ziua nu există, se folosește ultima zi a lunii.','Alegerea recalculează grupările întregului istoric. Datele și sumele tranzacțiilor rămân neschimbate.','Salvează perioada','Perioadă actualizată','Păstrează perioada actuală',"Tipul perioadei","Indicatori și perioadă contabilă","Solduri"],
  el: ['Λογιστική περίοδος','Ημερολογιακός μήνας','Οικονομικός μήνας','Ημέρα έναρξης','Μπορείς να επιλέξεις τη συνήθη ημέρα πληρωμής. Αν η ημέρα δεν υπάρχει, χρησιμοποιείται η τελευταία ημέρα του μήνα.','Η επιλογή υπολογίζει ξανά τις ομαδοποιήσεις όλου του ιστορικού. Οι ημερομηνίες και τα ποσά των συναλλαγών δεν αλλάζουν.','Αποθήκευση περιόδου','Η περίοδος ενημερώθηκε','Διατήρηση τρέχουσας περιόδου',"Τύπος περιόδου","Μετρήσεις και λογιστική περίοδος","Υπόλοιπα"],
};
export function periodText(language: string, key: typeof keys[number]): string {
  return (rows[language] || rows.en)[keys.indexOf(key)];
}
export const periodTranslationRows = rows;
