const keys = ['title','calendar','financial','day','hint','retroactive','save','saved','keep','type','metrics','balances','calendarInfo','financialInfo','countingInfo'] as const;
const rows: Record<string,string[]> = {
  it: ['Periodo di bilancio','Mese solare','Mese finanziario','Giorno di inizio','Puoi scegliere il giorno in cui ricevi normalmente lo stipendio. Se il giorno non esiste, viene usato l’ultimo giorno del mese.','La scelta ricalcola i raggruppamenti di tutto lo storico. Le date e gli importi delle transazioni restano invariati.','Salva periodo','Periodo aggiornato','Mantieni il periodo attuale',"Tipo di periodo","Metriche e periodo di bilancio","Saldi",'**Il mese solare** va dal primo all’ultimo giorno del mese.','**Il mese finanziario** parte invece dal giorno scelto da te e termina il giorno precedente del mese successivo.','Le transazioni **non cambiano**: cambia solo il periodo in cui vengono conteggiate.'],
  en: ['Accounting period','Calendar month','Financial month','Start day','You can choose your usual payday. If the day does not exist, the last day of the month is used.','This choice recalculates groupings across your history. Transaction dates and amounts stay unchanged.','Save period','Period updated','Keep current period',"Period type","Metrics and accounting period","Balances",'**The calendar month** runs from the first to the last day of the month.','**The financial month** starts on the day you choose and ends the day before the same date in the following month.','Transactions **do not change**: only the period in which they are counted changes.'],
  es: ['Periodo contable','Mes natural','Mes financiero','Día de inicio','Puedes elegir el día habitual de cobro. Si el día no existe, se usa el último día del mes.','La elección recalcula las agrupaciones de todo el historial. Las fechas y los importes de las transacciones se mantienen.','Guardar periodo','Periodo actualizado','Mantener el periodo actual',"Tipo de periodo","Métricas y periodo contable","Saldos",'**El mes natural** va del primer al último día del mes.','**El mes financiero** comienza el día que elijas y termina el día anterior a esa misma fecha del mes siguiente.','Las transacciones **no cambian**: solo cambia el período en el que se contabilizan.'],
  fr: ['Période comptable','Mois civil','Mois financier','Jour de début','Vous pouvez choisir votre jour de paie habituel. Si ce jour n’existe pas, le dernier jour du mois est utilisé.','Ce choix recalcule les regroupements de tout l’historique. Les dates et les montants des transactions restent inchangés.','Enregistrer la période','Période mise à jour','Conserver la période actuelle',"Type de période","Indicateurs et période comptable","Soldes",'**Le mois civil** va du premier au dernier jour du mois.','**Le mois financier** commence le jour que vous choisissez et se termine la veille de cette même date le mois suivant.','Les transactions **ne changent pas** : seule la période dans laquelle elles sont comptabilisées change.'],
  de: ['Abrechnungszeitraum','Kalendermonat','Finanzmonat','Starttag','Du kannst deinen üblichen Zahltag wählen. Gibt es den Tag nicht, wird der letzte Tag des Monats verwendet.','Die Auswahl berechnet die Gruppierungen des gesamten Verlaufs neu. Datum und Betrag der Transaktionen bleiben unverändert.','Zeitraum speichern','Zeitraum aktualisiert','Aktuellen Zeitraum beibehalten',"Zeitraumtyp","Kennzahlen und Abrechnungszeitraum","Salden",'**Der Kalendermonat** geht vom ersten bis zum letzten Tag des Monats.','**Der Finanzmonat** beginnt an dem von dir gewählten Tag und endet am Tag vor demselben Datum im Folgemonat.','Die Transaktionen **ändern sich nicht**: Es ändert sich nur der Zeitraum, in dem sie berücksichtigt werden.'],
  pt: ['Período contabilístico','Mês civil','Mês financeiro','Dia de início','Podes escolher o dia habitual de pagamento. Se o dia não existir, é usado o último dia do mês.','A escolha recalcula os agrupamentos de todo o histórico. As datas e os valores das transações não mudam.','Guardar período','Período atualizado','Manter o período atual',"Tipo de período","Métricas e período contabilístico","Saldos",'**O mês civil** vai do primeiro ao último dia do mês.','**O mês financeiro** começa no dia que escolheres e termina no dia anterior à mesma data do mês seguinte.','As transações **não mudam**: muda apenas o período em que são contabilizadas.'],
  pl: ['Okres rozliczeniowy','Miesiąc kalendarzowy','Miesiąc finansowy','Dzień rozpoczęcia','Możesz wybrać zwykły dzień wypłaty. Jeśli dany dzień nie istnieje, używany jest ostatni dzień miesiąca.','Wybór przelicza grupowanie całej historii. Daty i kwoty transakcji pozostają bez zmian.','Zapisz okres','Okres zaktualizowany','Zachowaj bieżący okres',"Typ okresu","Wskaźniki i okres rozliczeniowy","Salda",'**Miesiąc kalendarzowy** trwa od pierwszego do ostatniego dnia miesiąca.','**Miesiąc finansowy** zaczyna się w wybranym przez Ciebie dniu i kończy dzień przed tą samą datą w następnym miesiącu.','Transakcje **się nie zmieniają**: zmienia się tylko okres, do którego są przypisywane.'],
  nl: ['Boekhoudperiode','Kalendermaand','Financiële maand','Begindag','Je kunt je gebruikelijke betaaldag kiezen. Als de dag niet bestaat, wordt de laatste dag van de maand gebruikt.','Deze keuze herberekent de groeperingen van je volledige geschiedenis. Transactiedatums en bedragen blijven gelijk.','Periode opslaan','Periode bijgewerkt','Huidige periode behouden',"Periodetype","Statistieken en boekhoudperiode","Saldi",'**De kalendermaand** loopt van de eerste tot de laatste dag van de maand.','**De financiële maand** begint op de dag die je kiest en eindigt op de dag vóór dezelfde datum in de volgende maand.','De transacties **veranderen niet**: alleen de periode waarin ze worden meegerekend verandert.'],
  ro: ['Perioadă contabilă','Lună calendaristică','Lună financiară','Zi de început','Poți alege ziua obișnuită de salariu. Dacă ziua nu există, se folosește ultima zi a lunii.','Alegerea recalculează grupările întregului istoric. Datele și sumele tranzacțiilor rămân neschimbate.','Salvează perioada','Perioadă actualizată','Păstrează perioada actuală',"Tipul perioadei","Indicatori și perioadă contabilă","Solduri",'**Luna calendaristică** începe în prima zi și se termină în ultima zi a lunii.','**Luna financiară** începe în ziua aleasă de tine și se termină cu o zi înainte de aceeași dată din luna următoare.','Tranzacțiile **nu se modifică**: se schimbă doar perioada în care sunt luate în calcul.'],
  el: ['Λογιστική περίοδος','Ημερολογιακός μήνας','Οικονομικός μήνας','Ημέρα έναρξης','Μπορείς να επιλέξεις τη συνήθη ημέρα πληρωμής. Αν η ημέρα δεν υπάρχει, χρησιμοποιείται η τελευταία ημέρα του μήνα.','Η επιλογή υπολογίζει ξανά τις ομαδοποιήσεις όλου του ιστορικού. Οι ημερομηνίες και τα ποσά των συναλλαγών δεν αλλάζουν.','Αποθήκευση περιόδου','Η περίοδος ενημερώθηκε','Διατήρηση τρέχουσας περιόδου',"Τύπος περιόδου","Μετρήσεις και λογιστική περίοδος","Υπόλοιπα",'**Ο ημερολογιακός μήνας** διαρκεί από την πρώτη έως την τελευταία ημέρα του μήνα.','**Ο οικονομικός μήνας** ξεκινά την ημέρα που επιλέγεις και τελειώνει την προηγούμενη ημέρα από την ίδια ημερομηνία του επόμενου μήνα.','Οι συναλλαγές **δεν αλλάζουν**: αλλάζει μόνο η περίοδος στην οποία υπολογίζονται.'],
};
export function periodText(language: string, key: typeof keys[number]): string {
  return (rows[language] || rows.en)[keys.indexOf(key)];
}
export const periodTranslationRows = rows;
