const keys=['allCategories','expenseCategory','incomeCategory','alert','informationAction','confirmationAction','scopeHint','conditionsHint','active','inactive','empty','message','appliesTo','allConditions','anyCondition','and','or'] as const;
export const ruleEditorRows={
it:['Tutte le categorie','Categoria di spesa','Categoria di entrata','Avviso','Mostra un avviso','Chiedi conferma','La regola si applica solo ai movimenti e alla categoria scelti qui.','Le condizioni seguenti vengono controllate solo per i movimenti scelti sopra.','Attiva','Disattivata','Crea una regola per completare i movimenti o chiedere conferma quando un importo è insolito.','Testo del messaggio','Si applica a','Devono essere vere tutte le condizioni','Basta che sia vera almeno una condizione',"e","oppure"],
en:['All categories','Expense category','Income category','Alert','Show a message','Ask for confirmation','The rule applies only to the transactions and category selected here.','The following conditions are checked only for the transactions selected above.','Enabled','Disabled','Create a rule to complete transactions or ask for confirmation when an amount is unusual.','Message text','Applies to','All conditions must be true','At least one condition must be true',"and","or"],
es:['Todas las categorías','Categoría de gasto','Categoría de ingreso','Aviso','Mostrar un aviso','Pedir confirmación','La regla solo se aplica a los movimientos y la categoría seleccionados aquí.','Las condiciones siguientes solo se comprueban para los movimientos seleccionados arriba.','Activa','Desactivada','Crea una regla para completar movimientos o pedir confirmación cuando un importe sea inusual.','Texto del mensaje','Se aplica a','Deben cumplirse todas las condiciones','Basta con que se cumpla una condición',"y","o"],
fr:['Toutes les catégories','Catégorie de dépense','Catégorie de revenu','Alerte','Afficher un message','Demander confirmation','La règle ne concerne que les opérations et la catégorie choisies ici.','Les conditions suivantes ne sont vérifiées que pour les opérations choisies ci-dessus.','Activée','Désactivée','Créez une règle pour compléter les opérations ou demander confirmation pour un montant inhabituel.','Texte du message','S’applique à','Toutes les conditions doivent être remplies','Au moins une condition doit être remplie',"et","ou"],
de:['Alle Kategorien','Ausgabenkategorie','Einnahmenkategorie','Hinweis','Hinweis anzeigen','Bestätigung anfordern','Die Regel gilt nur für die hier gewählten Buchungen und die Kategorie.','Die folgenden Bedingungen werden nur für die oben gewählten Buchungen geprüft.','Aktiv','Deaktiviert','Erstelle eine Regel, um Buchungen zu ergänzen oder ungewöhnliche Beträge bestätigen zu lassen.','Nachrichtentext','Gilt für','Alle Bedingungen müssen erfüllt sein','Mindestens eine Bedingung muss erfüllt sein',"und","oder"],
pt:['Todas as categorias','Categoria de despesa','Categoria de receita','Aviso','Mostrar um aviso','Pedir confirmação','A regra aplica-se apenas aos movimentos e à categoria escolhidos aqui.','As condições seguintes são verificadas apenas para os movimentos escolhidos acima.','Ativa','Desativada','Crie uma regra para completar movimentos ou pedir confirmação quando um valor for invulgar.','Texto da mensagem','Aplica-se a','Todas as condições devem ser verdadeiras','Pelo menos uma condição deve ser verdadeira',"e","ou"],
pl:['Wszystkie kategorie','Kategoria wydatku','Kategoria przychodu','Powiadomienie','Pokaż wiadomość','Poproś o potwierdzenie','Reguła dotyczy tylko wybranych tutaj transakcji i kategorii.','Poniższe warunki są sprawdzane tylko dla transakcji wybranych powyżej.','Aktywna','Wyłączona','Utwórz regułę uzupełniającą transakcje lub proszącą o potwierdzenie nietypowej kwoty.','Treść wiadomości','Dotyczy','Wszystkie warunki muszą być spełnione','Wystarczy spełnienie jednego warunku',"i","lub"],
nl:['Alle categorieën','Uitgavencategorie','Inkomstencategorie','Melding','Toon een melding','Vraag om bevestiging','De regel geldt alleen voor de hier gekozen transacties en categorie.','De volgende voorwaarden worden alleen gecontroleerd voor de hierboven gekozen transacties.','Actief','Uitgeschakeld','Maak een regel om transacties aan te vullen of een ongebruikelijk bedrag te laten bevestigen.','Berichttekst','Van toepassing op','Alle voorwaarden moeten waar zijn','Minstens één voorwaarde moet waar zijn',"en","of"],
ro:['Toate categoriile','Categorie de cheltuieli','Categorie de venituri','Alertă','Arată un mesaj','Cere confirmare','Regula se aplică doar tranzacțiilor și categoriei alese aici.','Condițiile următoare sunt verificate doar pentru tranzacțiile alese mai sus.','Activă','Dezactivată','Creează o regulă pentru a completa tranzacții sau a cere confirmare pentru o sumă neobișnuită.','Textul mesajului','Se aplică la','Toate condițiile trebuie îndeplinite','Este suficientă îndeplinirea unei condiții',"și","sau"],
el:['Όλες οι κατηγορίες','Κατηγορία εξόδων','Κατηγορία εσόδων','Ειδοποίηση','Εμφάνιση μηνύματος','Αίτημα επιβεβαίωσης','Ο κανόνας ισχύει μόνο για τις συναλλαγές και την κατηγορία που επιλέχθηκαν εδώ.','Οι παρακάτω συνθήκες ελέγχονται μόνο για τις συναλλαγές που επιλέχθηκαν παραπάνω.','Ενεργός','Ανενεργός','Δημιουργήστε κανόνα για συμπλήρωση συναλλαγών ή επιβεβαίωση ασυνήθιστου ποσού.','Κείμενο μηνύματος','Ισχύει για','Πρέπει να ισχύουν όλες οι συνθήκες','Αρκεί να ισχύει μία συνθήκη',"και","ή"]
};
export function ruleEditorText(lang:string,key:typeof keys[number]){return (ruleEditorRows[lang]||ruleEditorRows.it)[keys.indexOf(key)];}
