const keys=['conflict','fix','explicit','priority','missing','details','more','result','applied'] as const;
export const ruleDiagnosticsRows={
it:['Questa regola non può attivarsi: la categoria scelta in QUANDO è incompatibile con le condizioni in SE.','Usa la categoria delle condizioni','Mantengo la scelta esplicita: la regola non la sostituisce.','Vale la prima azione applicata.','La categoria o il pagamento non è più disponibile.','Condizioni e azioni','Altre azioni','Risultato della prova','Impostato dalla regola'],
en:['This rule cannot run: the category selected in WHEN conflicts with the IF conditions.','Use the category from the conditions','Your explicit choice is kept; the rule does not replace it.','The first applied action takes priority.','The category or payment method is no longer available.','Conditions and actions','More actions','Test result','Set by the rule'],
es:['Esta regla no puede activarse: la categoría de CUANDO es incompatible con las condiciones de SI.','Usar la categoría de las condiciones','Se conserva tu elección explícita; la regla no la sustituye.','Tiene prioridad la primera acción aplicada.','La categoría o el método de pago ya no está disponible.','Condiciones y acciones','Más acciones','Resultado de la prueba','Establecido por la regla'],
fr:['Cette règle ne peut pas se déclencher : la catégorie de QUAND contredit les conditions de SI.','Utiliser la catégorie des conditions','Votre choix explicite est conservé ; la règle ne le remplace pas.','La première action appliquée est prioritaire.','La catégorie ou le moyen de paiement n’est plus disponible.','Conditions et actions','Autres actions','Résultat du test','Défini par la règle'],
de:['Diese Regel kann nicht greifen: Die Kategorie unter WENN widerspricht den Bedingungen unter FALLS.','Kategorie aus den Bedingungen verwenden','Deine ausdrückliche Auswahl bleibt erhalten.','Die zuerst angewendete Aktion hat Vorrang.','Kategorie oder Zahlungsmethode ist nicht mehr verfügbar.','Bedingungen und Aktionen','Weitere Aktionen','Testergebnis','Von der Regel festgelegt'],
pt:['Esta regra não pode ser ativada: a categoria em QUANDO contradiz as condições em SE.','Usar a categoria das condições','A sua escolha explícita é mantida; a regra não a substitui.','A primeira ação aplicada tem prioridade.','A categoria ou o método de pagamento já não está disponível.','Condições e ações','Mais ações','Resultado do teste','Definido pela regra'],
pl:['Ta reguła nie może zadziałać: kategoria w KIEDY jest sprzeczna z warunkami JEŚLI.','Użyj kategorii z warunków','Twój wyraźny wybór zostaje zachowany.','Pierwsza zastosowana akcja ma pierwszeństwo.','Kategoria lub metoda płatności nie jest już dostępna.','Warunki i akcje','Więcej akcji','Wynik testu','Ustawione przez regułę'],
nl:['Deze regel kan niet werken: de categorie bij WANNEER is strijdig met de voorwaarden bij ALS.','Gebruik de categorie uit de voorwaarden','Je expliciete keuze blijft behouden.','De eerste toegepaste actie heeft voorrang.','De categorie of betaalmethode is niet meer beschikbaar.','Voorwaarden en acties','Meer acties','Testresultaat','Ingesteld door de regel'],
ro:['Regula nu se poate activa: categoria din CÂND contrazice condițiile din DACĂ.','Folosește categoria din condiții','Alegerea ta explicită este păstrată.','Prima acțiune aplicată are prioritate.','Categoria sau metoda de plată nu mai este disponibilă.','Condiții și acțiuni','Mai multe acțiuni','Rezultatul testului','Stabilit de regulă'],
el:['Ο κανόνας δεν μπορεί να ενεργοποιηθεί: η κατηγορία στο ΟΤΑΝ συγκρούεται με τις συνθήκες ΑΝ.','Χρήση της κατηγορίας των συνθηκών','Η ρητή επιλογή σας διατηρείται.','Η πρώτη εφαρμοσμένη ενέργεια έχει προτεραιότητα.','Η κατηγορία ή ο τρόπος πληρωμής δεν είναι πλέον διαθέσιμος.','Συνθήκες και ενέργειες','Περισσότερες ενέργειες','Αποτέλεσμα δοκιμής','Ορίστηκε από τον κανόνα']
};
export function ruleDiagnosticText(lang:string,key:typeof keys[number]){return (ruleDiagnosticsRows[lang]||ruleDiagnosticsRows.it)[keys.indexOf(key)];}
