const keys=['title','review','real','deposited','available','residual','confirm','closed','hint','error','cover','uncovered','partial','covered','remaining','deficits','overlap','overallocated','depositLock','coverage','snapshot','empty'] as const;
export const closureTranslationRows={
it:['Chiusura del periodo','Rivedi ripartizione','Risparmio reale','Già versato nel periodo','Disponibile da ripartire','Residuo del periodo','Conferma chiusura','Periodo chiuso','Modifica gli importi proposti. Il residuo resta in questo periodo e non passa al successivo.','Operazione non riuscita. Riapri la ripartizione e controlla gli importi.','Copri deficit','Non coperto','Parzialmente coperto','Coperto','Ancora da coprire','Deficit dei periodi chiusi','Questo intervallo si sovrappone a un periodo già chiuso. Ripristina la precedente impostazione del periodo per consultarlo.','I versamenti registrati superano il risparmio reale: controllali prima della chiusura.','Versamento incluso in un periodo chiuso: non è più modificabile.','Copertura deficit','Importi registrati alla chiusura. Le modifiche successive ai movimenti non cambiano questo riepilogo.','Nessuna sotto-voce attiva: il risparmio resterà nel residuo del periodo.'],
en:['Period closing','Review allocation','Actual savings','Already deposited in this period','Available to allocate','Period remainder','Confirm closing','Period closed','Edit the proposed amounts. The remainder stays in this period and does not carry forward.','Unable to complete. Reopen the allocation and check the amounts.','Cover deficit','Uncovered','Partially covered','Covered','Still to cover','Closed-period deficits','This range overlaps a closed period. Restore the previous period setting to view it.','Recorded deposits exceed actual savings: check them before closing.','This deposit belongs to a closed period and cannot be edited.','Deficit coverage','Amounts recorded at closing. Later transaction changes do not change this summary.','No active savings categories: savings will remain in this period.'],
es:['Cierre del período','Revisar reparto','Ahorro real','Ya depositado en el período','Disponible para repartir','Remanente del período','Confirmar cierre','Período cerrado','Modifica los importes propuestos. El remanente queda en este período y no pasa al siguiente.','No se pudo completar. Abre de nuevo el reparto y revisa los importes.','Cubrir déficit','Sin cubrir','Cubierto parcialmente','Cubierto','Pendiente de cubrir','Déficits de períodos cerrados','Este intervalo se solapa con un período cerrado. Restablece la configuración anterior para consultarlo.','Los depósitos superan el ahorro real: revísalos antes del cierre.','Este depósito pertenece a un período cerrado y no puede modificarse.','Cobertura del déficit','Importes registrados al cierre. Los cambios posteriores en movimientos no modifican este resumen.','No hay subcategorías activas: el ahorro quedará en este período.'],
fr:['Clôture de la période','Vérifier la répartition','Épargne réelle','Déjà versé sur la période','Disponible à répartir','Reliquat de la période','Confirmer la clôture','Période clôturée','Modifiez les montants proposés. Le reliquat reste dans cette période et ne sera pas reporté.','Échec de l’opération. Rouvrez la répartition et vérifiez les montants.','Couvrir le déficit','Non couvert','Partiellement couvert','Couvert','Reste à couvrir','Déficits des périodes clôturées','Cet intervalle chevauche une période clôturée. Rétablissez le réglage précédent pour la consulter.','Les versements dépassent l’épargne réelle : vérifiez-les avant la clôture.','Ce versement appartient à une période clôturée et ne peut plus être modifié.','Couverture du déficit','Montants enregistrés à la clôture. Les modifications ultérieures des opérations ne changent pas ce résumé.','Aucune sous-catégorie active : l’épargne restera dans cette période.'],
de:['Periodenabschluss','Verteilung prüfen','Tatsächliche Ersparnis','Bereits in dieser Periode eingezahlt','Verfügbar zur Verteilung','Restbetrag der Periode','Abschluss bestätigen','Periode abgeschlossen','Ändere die vorgeschlagenen Beträge. Der Rest bleibt in dieser Periode und wird nicht übertragen.','Vorgang fehlgeschlagen. Öffne die Verteilung erneut und prüfe die Beträge.','Defizit decken','Nicht gedeckt','Teilweise gedeckt','Gedeckt','Noch zu decken','Defizite abgeschlossener Perioden','Dieser Zeitraum überschneidet sich mit einer abgeschlossenen Periode. Stelle die vorherige Periodeneinstellung wieder her.','Die Einzahlungen übersteigen die tatsächliche Ersparnis: Prüfe sie vor dem Abschluss.','Diese Einzahlung gehört zu einer abgeschlossenen Periode und kann nicht geändert werden.','Defizitdeckung','Beim Abschluss erfasste Beträge. Spätere Buchungsänderungen ändern diese Übersicht nicht.','Keine aktiven Sparunterkategorien: Die Ersparnis bleibt in dieser Periode.'],
pt:['Fecho do período','Rever distribuição','Poupança real','Já depositado no período','Disponível para distribuir','Restante do período','Confirmar fecho','Período fechado','Altere os valores propostos. O restante fica neste período e não passa ao seguinte.','Não foi possível concluir. Reabra a distribuição e verifique os valores.','Cobrir défice','Não coberto','Parcialmente coberto','Coberto','Ainda por cobrir','Défices de períodos fechados','Este intervalo sobrepõe-se a um período fechado. Restaure a configuração anterior para o consultar.','Os depósitos excedem a poupança real: verifique-os antes do fecho.','Este depósito pertence a um período fechado e não pode ser alterado.','Cobertura do défice','Valores registados no fecho. Alterações posteriores dos movimentos não alteram este resumo.','Sem subcategorias ativas: a poupança ficará neste período.'],
pl:['Zamknięcie okresu','Sprawdź podział','Rzeczywiste oszczędności','Już wpłacono w okresie','Dostępne do podziału','Pozostałość okresu','Potwierdź zamknięcie','Okres zamknięty','Zmień proponowane kwoty. Pozostałość zostaje w tym okresie i nie przechodzi na następny.','Operacja nie powiodła się. Otwórz podział ponownie i sprawdź kwoty.','Pokryj deficyt','Niepokryty','Częściowo pokryty','Pokryty','Pozostało do pokrycia','Deficyty zamkniętych okresów','Ten zakres nakłada się na zamknięty okres. Przywróć poprzednie ustawienie okresu, aby go zobaczyć.','Wpłaty przekraczają rzeczywiste oszczędności: sprawdź je przed zamknięciem.','Ta wpłata należy do zamkniętego okresu i nie można jej zmienić.','Pokrycie deficytu','Kwoty zapisane przy zamknięciu. Późniejsze zmiany transakcji nie zmieniają tego podsumowania.','Brak aktywnych podkategorii: oszczędności pozostaną w tym okresie.'],
nl:['Periode afsluiten','Verdeling bekijken','Werkelijke besparing','Al gestort in deze periode','Beschikbaar om te verdelen','Restant van de periode','Afsluiting bevestigen','Periode afgesloten','Pas de voorgestelde bedragen aan. Het restant blijft in deze periode en wordt niet overgedragen.','De bewerking is mislukt. Open de verdeling opnieuw en controleer de bedragen.','Tekort dekken','Niet gedekt','Gedeeltelijk gedekt','Gedekt','Nog te dekken','Tekorten van afgesloten perioden','Dit bereik overlapt een afgesloten periode. Herstel de vorige periode-instelling om deze te bekijken.','De stortingen zijn hoger dan de werkelijke besparing: controleer ze vóór afsluiting.','Deze storting hoort bij een afgesloten periode en kan niet worden gewijzigd.','Dekking van tekort','Bedragen bij afsluiting. Latere transactiewijzigingen veranderen dit overzicht niet.','Geen actieve spaarcategorieën: de besparing blijft in deze periode.'],
ro:['Închiderea perioadei','Verifică repartizarea','Economii reale','Deja depus în perioadă','Disponibil de repartizat','Restul perioadei','Confirmă închiderea','Perioadă închisă','Modifică sumele propuse. Restul rămâne în această perioadă și nu trece în următoarea.','Operațiunea a eșuat. Redeschide repartizarea și verifică sumele.','Acoperă deficitul','Neacoperit','Acoperit parțial','Acoperit','Rămas de acoperit','Deficite ale perioadelor închise','Intervalul se suprapune cu o perioadă închisă. Restabilește setarea anterioară pentru a o consulta.','Depunerile depășesc economiile reale: verifică-le înainte de închidere.','Această depunere aparține unei perioade închise și nu mai poate fi modificată.','Acoperirea deficitului','Sume înregistrate la închidere. Modificările ulterioare ale tranzacțiilor nu schimbă acest rezumat.','Nicio subcategorie activă: economiile rămân în această perioadă.'],
el:['Κλείσιμο περιόδου','Έλεγχος κατανομής','Πραγματική αποταμίευση','Ήδη κατατεθειμένα στην περίοδο','Διαθέσιμα για κατανομή','Υπόλοιπο περιόδου','Επιβεβαίωση κλεισίματος','Η περίοδος έκλεισε','Αλλάξτε τα προτεινόμενα ποσά. Το υπόλοιπο μένει σε αυτή την περίοδο και δεν μεταφέρεται στην επόμενη.','Η ενέργεια απέτυχε. Ανοίξτε ξανά την κατανομή και ελέγξτε τα ποσά.','Κάλυψη ελλείμματος','Ακάλυπτο','Μερικώς καλυμμένο','Καλυμμένο','Απομένει για κάλυψη','Ελλείμματα κλεισμένων περιόδων','Το διάστημα επικαλύπτει κλεισμένη περίοδο. Επαναφέρετε την προηγούμενη ρύθμιση για να τη δείτε.','Οι καταθέσεις υπερβαίνουν την πραγματική αποταμίευση: ελέγξτε τις πριν το κλείσιμο.','Αυτή η κατάθεση ανήκει σε κλεισμένη περίοδο και δεν μπορεί να αλλάξει.','Κάλυψη ελλείμματος','Ποσά κατά το κλείσιμο. Μεταγενέστερες αλλαγές συναλλαγών δεν αλλάζουν αυτή τη σύνοψη.','Δεν υπάρχουν ενεργές υποκατηγορίες: η αποταμίευση θα μείνει σε αυτή την περίοδο.']
};
export const closureHelpRows={
it:['La conferma registra un riepilogo definitivo e blocca le modifiche ai versamenti inclusi.','La copertura usa prima i fondi non assegnati a obiettivi; se servono altri fondi, diminuisce anche il risparmio degli obiettivi interessati.'],
en:['Confirmation records a final summary and locks the included deposits.','Coverage uses funds not assigned to goals first; if more funds are needed, the affected goals’ savings also decrease.'],
es:['La confirmación guarda un resumen definitivo y bloquea los depósitos incluidos.','La cobertura usa primero fondos sin objetivo; si hacen falta más, también disminuye el ahorro de los objetivos afectados.'],
fr:['La confirmation enregistre un résumé définitif et verrouille les versements inclus.','La couverture utilise d’abord les fonds sans objectif ; si nécessaire, elle réduit aussi l’épargne des objectifs concernés.'],
de:['Die Bestätigung speichert eine endgültige Übersicht und sperrt die enthaltenen Einzahlungen.','Die Deckung nutzt zuerst keinem Ziel zugeordnete Mittel. Falls nötig, sinkt auch die Ersparnis der betroffenen Ziele.'],
pt:['A confirmação guarda um resumo definitivo e bloqueia os depósitos incluídos.','A cobertura usa primeiro fundos sem objetivo; se forem necessários mais, também reduz a poupança dos objetivos afetados.'],
pl:['Potwierdzenie zapisuje ostateczne podsumowanie i blokuje uwzględnione wpłaty.','Pokrycie najpierw wykorzystuje środki bez celu; w razie potrzeby zmniejsza też oszczędności przypisane do celów.'],
nl:['Bevestiging legt een definitief overzicht vast en vergrendelt de opgenomen stortingen.','De dekking gebruikt eerst geld zonder spaardoel; zo nodig daalt ook het spaargeld van de betrokken doelen.'],
ro:['Confirmarea salvează un rezumat definitiv și blochează depunerile incluse.','Acoperirea folosește întâi fondurile fără obiectiv; dacă mai sunt necesare fonduri, scad și economiile obiectivelor afectate.'],
el:['Η επιβεβαίωση αποθηκεύει οριστική σύνοψη και κλειδώνει τις καταθέσεις που περιλαμβάνονται.','Η κάλυψη χρησιμοποιεί πρώτα χρήματα χωρίς στόχο· αν χρειαστούν περισσότερα, μειώνεται και η αποταμίευση των σχετικών στόχων.']
};
export function closureText(lang:string,key:typeof keys[number]|'closingHint'|'coverageHint'){
  if(key==='closingHint'||key==='coverageHint')return (closureHelpRows[lang]||closureHelpRows.it)[key==='closingHint'?0:1];
  return (closureTranslationRows[lang]||closureTranslationRows.it)[keys.indexOf(key)];
}
