const keys=['title','calculator','converter','history','convert','from','to','swap','rate','create','share','noProject','retention','clear','clearConfirm','empty','error','project','chooseCurrency','saved','busy'] as const;
export const toolsRows={
it:['Tool','Calcolatrice','Convertitore valute','Storico Tool','Converti','Da','A','Inverti conversione','Tasso','Crea transazione','Aggiungi a Share','Crea prima un progetto Share per utilizzare questa funzione.','Gli ultimi 7 giorni. I risultati più vecchi vengono eliminati automaticamente.','Cancella tutto','Cancellare tutti i risultati di questa sezione?','Nessun risultato recente.','Operazione non riuscita. Controlla l’importo e riprova.','Progetto Share','Scegli valuta','Salvato nello storico','Attendi…'],
en:['Tools','Calculator','Currency converter','Tool history','Convert','From','To','Reverse conversion','Rate','Create transaction','Add to Share','Create a Share project first to use this feature.','The last 7 days. Older results are deleted automatically.','Clear all','Delete all results in this section?','No recent results.','Unable to complete. Check the amount and try again.','Share project','Choose currency','Saved to history','Please wait…'],
es:['Herramientas','Calculadora','Conversor de divisas','Historial de herramientas','Convertir','De','A','Invertir conversión','Tipo de cambio','Crear transacción','Añadir a Share','Crea primero un proyecto Share para usar esta función.','Los últimos 7 días. Los resultados anteriores se eliminan automáticamente.','Borrar todo','¿Borrar todos los resultados de esta sección?','No hay resultados recientes.','No se pudo completar. Comprueba el importe e inténtalo de nuevo.','Proyecto Share','Elegir moneda','Guardado en el historial','Espera…'],
fr:['Outils','Calculatrice','Convertisseur de devises','Historique des outils','Convertir','De','Vers','Inverser la conversion','Taux','Créer une transaction','Ajouter à Share','Créez d’abord un projet Share pour utiliser cette fonction.','Les 7 derniers jours. Les anciens résultats sont supprimés automatiquement.','Tout effacer','Supprimer tous les résultats de cette section ?','Aucun résultat récent.','Impossible de terminer. Vérifiez le montant et réessayez.','Projet Share','Choisir une devise','Enregistré dans l’historique','Patientez…'],
de:['Tools','Rechner','Währungsrechner','Tool-Verlauf','Umrechnen','Von','Nach','Umrechnung umkehren','Kurs','Buchung erstellen','Zu Share hinzufügen','Erstelle zuerst ein Share-Projekt, um diese Funktion zu nutzen.','Die letzten 7 Tage. Ältere Ergebnisse werden automatisch gelöscht.','Alles löschen','Alle Ergebnisse dieses Bereichs löschen?','Keine aktuellen Ergebnisse.','Vorgang fehlgeschlagen. Prüfe den Betrag und versuche es erneut.','Share-Projekt','Währung wählen','Im Verlauf gespeichert','Bitte warten…'],
pt:['Ferramentas','Calculadora','Conversor de moedas','Histórico de ferramentas','Converter','De','Para','Inverter conversão','Taxa','Criar transação','Adicionar ao Share','Crie primeiro um projeto Share para usar esta função.','Os últimos 7 dias. Os resultados antigos são eliminados automaticamente.','Apagar tudo','Apagar todos os resultados desta secção?','Sem resultados recentes.','Não foi possível concluir. Verifique o valor e tente novamente.','Projeto Share','Escolher moeda','Guardado no histórico','Aguarde…'],
pl:['Narzędzia','Kalkulator','Przelicznik walut','Historia narzędzi','Przelicz','Z','Na','Odwróć przeliczenie','Kurs','Utwórz transakcję','Dodaj do Share','Najpierw utwórz projekt Share, aby użyć tej funkcji.','Ostatnie 7 dni. Starsze wyniki są usuwane automatycznie.','Wyczyść wszystko','Usunąć wszystkie wyniki tej sekcji?','Brak ostatnich wyników.','Nie udało się zakończyć. Sprawdź kwotę i spróbuj ponownie.','Projekt Share','Wybierz walutę','Zapisano w historii','Poczekaj…'],
nl:['Tools','Rekenmachine','Valutaomrekenaar','Toolgeschiedenis','Omrekenen','Van','Naar','Omrekening omkeren','Koers','Transactie maken','Toevoegen aan Share','Maak eerst een Share-project om deze functie te gebruiken.','De laatste 7 dagen. Oudere resultaten worden automatisch verwijderd.','Alles wissen','Alle resultaten in dit onderdeel verwijderen?','Geen recente resultaten.','Kan niet voltooien. Controleer het bedrag en probeer opnieuw.','Share-project','Valuta kiezen','Opgeslagen in geschiedenis','Even geduld…'],
ro:['Instrumente','Calculator','Convertor valutar','Istoricul instrumentelor','Convertește','Din','În','Inversează conversia','Curs','Creează tranzacție','Adaugă în Share','Creează mai întâi un proiect Share pentru această funcție.','Ultimele 7 zile. Rezultatele mai vechi sunt șterse automat.','Șterge tot','Ștergi toate rezultatele din această secțiune?','Niciun rezultat recent.','Operația nu a reușit. Verifică suma și încearcă din nou.','Proiect Share','Alege moneda','Salvat în istoric','Așteaptă…'],
el:['Εργαλεία','Αριθμομηχανή','Μετατροπέας νομισμάτων','Ιστορικό εργαλείων','Μετατροπή','Από','Σε','Αντιστροφή μετατροπής','Ισοτιμία','Δημιουργία συναλλαγής','Προσθήκη στο Share','Δημιουργήστε πρώτα ένα έργο Share για αυτή τη λειτουργία.','Οι τελευταίες 7 ημέρες. Τα παλαιότερα αποτελέσματα διαγράφονται αυτόματα.','Διαγραφή όλων','Διαγραφή όλων των αποτελεσμάτων αυτής της ενότητας;','Δεν υπάρχουν πρόσφατα αποτελέσματα.','Η ενέργεια απέτυχε. Ελέγξτε το ποσό και δοκιμάστε ξανά.','Έργο Share','Επιλογή νομίσματος','Αποθηκεύτηκε στο ιστορικό','Περιμένετε…']
};
export function toolsText(lang:string,key:typeof keys[number]){return (toolsRows[lang]||toolsRows.it)[keys.indexOf(key)];}
